language: python
cache: apt

python:
    - "2.6"

env:
    global:
        - FORCE_DB=1
        - PYTHONPATH=.
        - DJANGO_SETTINGS_MODULE=settings_travis
        - DEBIAN_FRONTEND=noninteractive
        - CFLAGS="-O0"

services:
    - memcached

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install build-essential aria2 libxml2-dev libxslt-dev libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev zlib1g-dev sqlite3 libtidy-dev
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib
    - aria2c -j 10 https://s3-us-west-2.amazonaws.com/pkgs.mozilla.net/python/mdn/product_details_json.tar.gz
    - aria2c -j 10 https://s3-us-west-2.amazonaws.com/pkgs.mozilla.net/locale/mdn/locale.tar.gz
    - tar -C .. -zxf product_details_json.tar.gz
    - tar xvfz locale.tar.gz
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.13.deb
    - sudo dpkg --force-confdef -i elasticsearch-0.90.13.deb
    - sudo service elasticsearch start

install:
    - pip install -U pip coveralls
    - pip install -r requirements/compiled.txt

before_script:
    - mysql -e 'create database kuma;'

script:
    - coverage run --include=`pwd`/kuma/*,`pwd`/apps/* manage.py test --noinput -v2 kuma

after_success:
    - coveralls

notifications:
    irc:
        channels:
            - "irc.mozilla.org#mdndev"
        on_success: always
        on_failure: always
        use_notice: true
