# Default config for Vagrant
#
# Don't change this; use vagrantconfig_local.yaml to override these settings
# instead.

nfs: true
gui: false
ip_address: 192.168.10.55
memory_size: 768
number_cpus: 2
box: "kuma-ubuntu"
virtual_box_url: "https://s3-us-west-2.amazonaws.com/pkgs.mozilla.net/vagrant/mdn/kuma-ubuntu-20140129.box"
package_name: "kuma-ubuntu.box"
mount_point: "/home/vagrant/src"
